# Generated by Django 4.1.4 on 2022-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
