# Generated by Django 4.1.4 on 2022-12-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employe_delete_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='salary',
        ),
    ]
